In [2]:
import torch

### Matrix Construction

In [10]:
torch.randn(2,3,4)
torch.zeros(4,4)
#Diagonal Matrix
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

### Convert numpy into torch

In [13]:
import numpy as np
x = np.array([1,2,3,4])
torch.from_numpy(x)

tensor([1, 2, 3, 4], dtype=torch.int32)

### The dimension needs to be mentioned 
### if the input is a matrix in order to search minimum values along rows or columns.

In [14]:
d = torch.randn(4,5)
torch.argmin(d,dim=1)
torch.argmax(d,dim=1)

tensor([3, 1, 0, 1])

### Calculation

In [16]:
d = torch.randn(4,5)
d

tensor([[-0.8812,  1.0178,  0.3404, -1.0066, -0.8239],
        [-0.1608, -1.2331,  0.4347,  1.6147, -0.2919],
        [-1.3907,  0.7406, -0.8014,  0.5924, -0.0649],
        [-0.9049, -1.0436,  0.9001, -1.6543,  2.7241]])

In [17]:
d.t()

tensor([[-0.8812, -0.1608, -1.3907, -0.9049],
        [ 1.0178, -1.2331,  0.7406, -1.0436],
        [ 0.3404,  0.4347, -0.8014,  0.9001],
        [-1.0066,  1.6147,  0.5924, -1.6543],
        [-0.8239, -0.2919, -0.0649,  2.7241]])

In [22]:
d = torch.randn(4,5)
torch.unbind(d,1)

(tensor([-0.8812, -0.1608, -1.3907, -0.9049]),
 tensor([ 1.0178, -1.2331,  0.7406, -1.0436]),
 tensor([ 0.3404,  0.4347, -0.8014,  0.9001]),
 tensor([-1.0066,  1.6147,  0.5924, -1.6543]),
 tensor([-0.8239, -0.2919, -0.0649,  2.7241]))

In [23]:
d = torch.randn(4,5)
torch.add(d,20)

tensor([[19.7613, 19.0857, 20.7088, 19.2958, 19.7676],
        [19.6747, 20.3043, 20.3808, 19.4542, 20.6057],
        [20.4575, 21.1654, 20.1513, 20.4278, 19.3676],
        [20.2377, 19.0366, 19.8177, 19.8822, 21.0658]])

In [24]:
d

tensor([[-0.2387, -0.9143,  0.7088, -0.7042, -0.2324],
        [-0.3253,  0.3043,  0.3808, -0.5458,  0.6057],
        [ 0.4575,  1.1654,  0.1513,  0.4278, -0.6324],
        [ 0.2377, -0.9634, -0.1823, -0.1178,  1.0658]])

In [25]:
torch.mul(d,100)

tensor([[-23.8698, -91.4338,  70.8839, -70.4235, -23.2421],
        [-32.5272,  30.4308,  38.0764, -54.5806,  60.5748],
        [ 45.7451, 116.5384,  15.1278,  42.7822, -63.2401],
        [ 23.7681, -96.3354, -18.2336, -11.7831, 106.5776]])

#### Round Up Function

In [27]:
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [29]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [30]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [ ]:
torch.sqrt()

### Indice

In [6]:
#默认的torch.Tensor是FloatTensor
x = torch.randn((3,4))
x.dtype

torch.float32