In [5]:
from __future__ import print_function

# Recipe 3-16. Initializing Weights in the Dropout Rate

In [1]:
#Initialize a random tensor

In [6]:
import numpy as np
import torch

In [7]:
torch.Tensor(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#From a uniform distribution

In [10]:
torch.manual_seed(1)

In [11]:
torch.Tensor(5, 3).uniform_(-1, 1)

tensor([[ 0.5153, -0.4414, -0.1939],
        [ 0.4694, -0.9414,  0.5997],
        [-0.2057,  0.5087,  0.1390],
        [-0.1224,  0.2774,  0.0493],
        [ 0.3652, -0.3897, -0.0729]])

In [12]:
#getting the shape of the tensor
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

torch.Size([5, 3])


In [13]:
#Creation from lists & numpy

In [14]:
z = torch.LongTensor([[1, 3], [2, 9]])
print(z.type())
# Cast to numpy ndarray
print(z.numpy().dtype)

torch.LongTensor
int64


In [15]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


# Recipe 3-17. Adding Math Operations Problem

In [16]:
#Simple mathematical operations

In [17]:
y = x * torch.randn(5, 3)
print(y)

tensor([[-9.5237e-02,  1.3944e-01, -1.5719e-03],
        [ 9.8974e-01, -1.6816e-01,  8.2311e-01],
        [-1.2762e+00,  6.6872e-04, -5.9525e-01],
        [ 4.3277e-01,  1.6542e-02,  3.0079e-01],
        [ 9.8996e-01,  1.7735e-01, -5.8985e-01]])


In [18]:
y = x / torch.sqrt(torch.randn(5, 3) ** 2)
print(y)

tensor([[-2.2189e-01,  9.5583e-02, -5.4559e-03],
        [ 3.8307e-01,  2.5760e-01, -3.3489e-01],
        [-2.7237e-01, -3.9267e-01, -4.2511e-01],
        [-1.7613e+00,  7.7451e-02,  1.5184e+01],
        [ 5.8684e-01, -1.0187e+00,  1.7620e+00]])


In [19]:
#Broadcasting


In [20]:

print (x.size())
y = x + torch.randn(5, 1)
print(y)

torch.Size([5, 3])
tensor([[-0.4940, -0.2590, -0.4079],
        [ 2.6326,  2.0696,  1.3860],
        [-1.0185, -0.5821, -0.8459],
        [ 0.5357,  0.9040,  1.4523],
        [ 0.1006, -1.4205,  0.1770]])


In [21]:
#Reshape

In [22]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).squeeze().size())
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


In [23]:
#Repeat

In [24]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


In [25]:
#Concatenate tensors

In [26]:
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])


In [27]:
#Advanced Indexing

In [28]:
y = torch.randn(2, 3, 4)
print(y[[1, 0, 1, 1]].size())

# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(y[rev_idx].size())

torch.Size([4, 3, 4])
torch.Size([2, 3, 4])


In [29]:
#Convolution, BatchNorm & Pooling Layers

In [33]:
from torch.autograd import Variable
import torch.nn as nn

x = Variable(torch.randn(10, 3, 28, 28))

conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3, 3), stride=1, 
                 padding=1, bias=True)
bn = nn.BatchNorm2d(num_features=32)
pool = nn.MaxPool2d(kernel_size=(2, 2), stride=2)

output_conv = bn(conv(x))
outpout_pool = pool(conv(x))

print('Conv output size : ', output_conv.size())
print('Pool output size : ', outpout_pool.size())

Conv output size :  torch.Size([10, 32, 28, 28])
Pool output size :  torch.Size([10, 32, 14, 14])


# Recipe 3-18. Embedding Layers in RNN Problem

In [34]:
#Recurrent, Embedding & Dropout Layers

In [35]:
inputs = [[1, 2, 3], [1, 0, 4], [1, 2, 4], [1, 4, 0], [1, 3, 3]]
x = Variable(torch.LongTensor(inputs))

embedding = nn.Embedding(num_embeddings=5, embedding_dim=20, padding_idx=1)
drop = nn.Dropout(p=0.5)
gru = nn.GRU(input_size=20, hidden_size=50, num_layers=2, batch_first=True, 
             bidirectional=True, dropout=0.3)

emb = drop(embedding(x))
gru_h, gru_h_t = gru(emb)

print('Embedding size : ', emb.size())
print('GRU hidden states size : ', gru_h.size())
print('GRU last hidden state size : ', gru_h_t.size())

Embedding size :  torch.Size([5, 3, 20])
GRU hidden states size :  torch.Size([5, 3, 100])
GRU last hidden state size :  torch.Size([4, 5, 50])


In [36]:
#The functional API provides users a way to use these classes in a functional way.

In [37]:
from torch.nn.functional import F
x = Variable(torch.randn(10, 3, 28, 28))
filters = Variable(torch.randn(32, 3, 3, 3))
conv_out = F.relu(F.dropout(F.conv2d(input=x, weight=filters, padding=1), 
                            p=0.5, training=True))

print('Conv output size : ', conv_out.size())

ImportError: cannot import name 'F' from 'torch.nn.functional' (c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\torch\nn\functional.py)