In [3]:
import torch

### Sampling

In [4]:
d = torch.tensor([10,10,13,10,34,56,43,45,34,56,5,67.])
torch.multinomial(d,5,replacement=True)

tensor([9, 6, 7, 6, 5])

In [5]:
torch.normal(mean=torch.arange(1.,11.),std=torch.arange(1,0,-0.1))

tensor([0.5884, 1.9182, 4.6726, 4.0981, 5.4906, 6.1405, 7.3714, 8.1323, 8.9270,
        9.9870])

https://pytorch-cn.readthedocs.io/zh/latest/notes/autograd/
#### Auto_gard

In [40]:
from torch.autograd import Variable

In [41]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [42]:
a,b=12,23
x1 = Variable(torch.randn(a,b),requires_grad=True)
x2 = Variable(torch.randn(a,b),requires_grad=True)
x3 = Variable(torch.randn(a,b),requires_grad=True)
c = x1 * x2
d = a +x3
e = torch.sum(d)

In [43]:
e.backward(retain_graph=True)

In [44]:
e

tensor(3295.8208, grad_fn=<SumBackward0>)

### Backward

In [24]:
import torch
import torch.nn as nn

x = torch.tensor([2, 3, 4], dtype=torch.float, requires_grad=True)
print(x)
y = x * 2
while y.norm() < 1000:
    y = y * 2
print(y)

y.backward(torch.ones_like(y))
print(x.grad)

tensor([2., 3., 4.], requires_grad=True)
tensor([ 512.,  768., 1024.], grad_fn=<MulBackward0>)
tensor([256., 256., 256.])


In [49]:
'''
torch.ones_like(y)
生成与y形状相同、元素全为1的张量
'''

'\ntorch.ones_like(y)\n生成与y形状相同、元素全为1的张量\n'

### Recipe2-3 Statistic(Ignored)

### 2-4. Gradient Computation

In [54]:
import torch
from torch.autograd import Variable

x_data = [11.,22.,33.]
y_data = [21.,14.,64.]
w = Variable(torch.Tensor([1.]), requires_grad=True)

#before training
print("predict (before training)",4,forward(4).data[0])

predict (before training) 4 tensor(4.)


In [55]:
# Using forward pass
def forward(x):
    return x*w

# Define the Loss function
def loss(x,y):
    y_pred = forward(x)
    return (y_pred-y)*(y_pred-y)

In [56]:
# Run the Training Loop
for epoch in range(10):
    for x_val,y_val in zip(x_data,y_data):
        l = loss(x_val,y_val)
        l.backward()
        print("\tgrad:", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        
        #Manually set the gradients to zero after updating weights
        w.grad.data.zero_()
        
print("progress:", epoch,l.data[0])

	grad: 11.0 21.0 tensor(-220.)
	grad: 22.0 14.0 tensor(2481.6001)
	grad: 33.0 64.0 tensor(-51303.6484)
	grad: 11.0 21.0 tensor(118461.7578)
	grad: 22.0 14.0 tensor(-671630.6875)
	grad: 33.0 64.0 tensor(13114108.)
	grad: 11.0 21.0 tensor(-30279010.)
	grad: 22.0 14.0 tensor(1.7199e+08)
	grad: 33.0 64.0 tensor(-3.3589e+09)
	grad: 11.0 21.0 tensor(7.7553e+09)
	grad: 22.0 14.0 tensor(-4.4050e+10)
	grad: 33.0 64.0 tensor(8.6030e+11)
	grad: 11.0 21.0 tensor(-1.9863e+12)
	grad: 22.0 14.0 tensor(1.1282e+13)
	grad: 33.0 64.0 tensor(-2.2034e+14)
	grad: 11.0 21.0 tensor(5.0875e+14)
	grad: 22.0 14.0 tensor(-2.8897e+15)
	grad: 33.0 64.0 tensor(5.6436e+16)
	grad: 11.0 21.0 tensor(-1.3030e+17)
	grad: 22.0 14.0 tensor(7.4013e+17)
	grad: 33.0 64.0 tensor(-1.4455e+19)
	grad: 11.0 21.0 tensor(3.3374e+19)
	grad: 22.0 14.0 tensor(-1.8957e+20)
	grad: 33.0 64.0 tensor(3.7022e+21)
	grad: 11.0 21.0 tensor(-8.5480e+21)
	grad: 22.0 14.0 tensor(4.8553e+22)
	grad: 33.0 64.0 tensor(-9.4824e+23)
	grad: 11.0 21.0 tens

In [60]:
w

tensor([-2.3172e+24], requires_grad=True)

In [59]:
print("predict(after training)",4,forward(4).data[0])

predict(after training) 4 tensor(-9.2687e+24)


In [77]:
from torch import FloatTensor
from torch.autograd import Variable

a = Variable(FloatTensor([5]))
weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (12, 53, 91, 73)]
w1, w2, w3, w4 = weights
print(w1)
b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
Loss = (10 - d)
Loss.backward()

tensor([12.], requires_grad=True)


In [78]:
for index, weight in enumerate(weights, start=1):
    print(weight.grad.data,'??')
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to Loss: {gradient}")

tensor([-455.]) ??
Gradient of w1 w.r.t to Loss: -455.0
tensor([-365.]) ??
Gradient of w2 w.r.t to Loss: -365.0
tensor([-60.]) ??
Gradient of w3 w.r.t to Loss: -60.0
tensor([-265.]) ??
Gradient of w4 w.r.t to Loss: -265.0


### 2-5. Tensor Operations

### torch.mul(a, b)是矩阵a和b对应位相乘，a和b的维度必须相等，比如a的维度是(1, 2)，b的维度是(1, 2)，返回的仍是(1, 2)的矩阵
### torch.mm(a, b)是矩阵a和b矩阵相乘，比如a的维度是(1, 2)，b的维度是(2, 3)，返回的就是(1, 3)的矩阵

In [79]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
# matrix multiplication
#torch.mul(a, b)是矩阵a和b对应位相乘，a和b的维度必须相等，比如a的维度是(1, 2)，b的维度是(1, 2)，返回的仍是(1, 2)的矩阵
z = torch.mm(x, y)
print(z.size())

torch.Size([4, 4])


In [85]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
print(z)

print('Requires Gradient : %s ' % (z.requires_grad))
print('Volatile : %s ' % (z.volatile))
print('Gradient : %s ' % (z.grad))
print(z.data)

tensor([[-2.7035,  4.6717, -0.4064,  2.0015],
        [ 1.2070,  1.3633, -0.2969, -3.1569],
        [ 3.4389, -0.5569, -4.8873, -1.8243],
        [-4.0354, -3.9926, -3.3342, -3.6767]])
Requires Gradient : False 
Volatile : False 
Gradient : None 
tensor([[-2.7035,  4.6717, -0.4064,  2.0015],
        [ 1.2070,  1.3633, -0.2969, -3.1569],
        [ 3.4389, -0.5569, -4.8873, -1.8243],
        [-4.0354, -3.9926, -3.3342, -3.6767]])


c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: UserWarning: volatile was removed (Variable.volatile is always False)
  """


### Recipe 2-6. Tensor Operations

In [86]:
x.data

#tensor operations
mat1 = torch.FloatTensor(4,4).uniform_(0,1)
print(mat1)

mat2 = torch.FloatTensor(5,4).uniform_(0,1)
print(mat2)

vec1 = torch.FloatTensor(4).uniform_(0,1)
print(vec1)

tensor([[0.5989, 0.8183, 0.6143, 0.4144],
        [0.4284, 0.5015, 0.9921, 0.4548],
        [0.8947, 0.2699, 0.9941, 0.6090],
        [0.0529, 0.2766, 0.0336, 0.1986]])
tensor([[0.5808, 0.3960, 0.7817, 0.9292],
        [0.4476, 0.1892, 0.4560, 0.5092],
        [0.6518, 0.9496, 0.7132, 0.2230],
        [0.0108, 0.7713, 0.5618, 0.9201],
        [0.6954, 0.4923, 0.6194, 0.6219]])
tensor([0.6794, 0.9086, 0.6197, 0.3217])


In [89]:
# scalar addition
mat1 + 10.5

# scalar subtraction
mat2 - 0.20

# vector and matrix addition
mat1 + vec1

tensor([[1.2784, 1.7269, 1.2340, 0.7361],
        [1.1078, 1.4101, 1.6118, 0.7765],
        [1.5741, 1.1785, 1.6138, 0.9307],
        [0.7323, 1.1852, 0.6534, 0.5202]])

In [97]:
print(torch.mm(mat2, mat1))
print(torch.mm(mat1, mat2))

tensor([[1.2659, 1.1419, 1.5579, 1.0813],
        [0.7840, 0.7251, 0.9331, 0.6504],
        [1.4470, 1.2638, 2.0589, 1.1806],
        [0.8882, 0.8018, 1.3613, 0.8801],
        [1.2143, 1.1551, 1.5521, 1.0127]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x4 and 5x4)

In [96]:
torch.mm(mat1, mat2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x4 and 5x4)

### Recipe 2-7. Distributions

In [103]:
# about Bernoulli distribution
from torch.distributions.bernoulli import Bernoulli

dist = Bernoulli(torch.tensor([0.3,0.6,0.9]))
dist

Bernoulli(probs: torch.Size([3]))

In [105]:
dist.sample() #sample is binary, it takes 1 with p and 0 with 1-p

tensor([1., 0., 0.])

In [106]:
#Creates a Bernoulli distribution parameterized by probs 
#Samples are binary (0 or 1). They take the value 1 with probability p 
#and 0 with probability 1 - p.